
# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  # secret_key_base: 98569eb067dd51110faddd52bfd48e707fb9e9a7bbdcda655a6c322f267e05f62f1e8b006853e6da7825121911cd5091aae99a02dc2426a73cf09840b2fb72a3

test:
  # secret_key_base: d037c7f0cbbaba3d55813eaf2d7e9fe5e54d79997cf2603ffbe192836aaa8d8a18c77edc4dcdb8553dadba4a6ce1cd7fc03a0198cfb0a30c7c427923f300e102

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
